<?php

namespace ShoeStore\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function find($id)
    {
		return $this->createQueryBuilder('s')
		->where('s.id = :id')
		->setParameter('id', $id)
		->getQuery().getResult();
    }
}
