<?php

namespace ShoeStore\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShoesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoesRepository extends EntityRepository
{
	public function findAllShoes()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM ShoeStoreProductBundle:Shoes s ORDER BY s.modelName ASC'
            )
            ->getResult();
    }
	
	public function findShoe($id)
    {
		return $this->createQueryBuilder('s')
		->where('s.id = :id')
		->setParameter('id', $id)
		->getQuery().getResult();
    }
	
	public function saveShoe($shoe)
    {
        return $this->getEntityManager()
            ->persist($shoe);
    }
}
