shoe_store_product:
    resource: "@ShoeStoreProductBundle/Resources/config/routing.yml"
    prefix:   /

ramon_demo:
    resource: "@RamonDemoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

#product_add:
#    path:     /createProduct
#    defaults: { _controller: AppBundle:Default:create }

# app/config/routing.yml
blog_list:
    path:     /blog
    defaults: { _controller: AppBundle:Blog:list }

blog_show:
    path:     /blog/show/{id}
    defaults: { _controller: AppBundle:Blog:show }